# Generated by Django 5.2.8 on 2025-11-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0002_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bache',
            old_name='usuario',
            new_name='vecino',
        ),
    ]
