# Generated by Django 5.2.8 on 2025-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0003_rename_usuario_bache_vecino'),
    ]

    operations = [
        migrations.AddField(
            model_name='bache',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bache',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
