# Generated by Django 5.2.8 on 2025-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0004_bache_latitud_bache_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='bache',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='baches/'),
        ),
    ]
