# Generated by Django 5.2.8 on 2025-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0005_bache_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bache',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
