# Generated by Django 5.2.8 on 2025-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0006_bache_fecha_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bache',
            name='comentario_municipio',
            field=models.TextField(blank=True),
        ),
    ]
