# Generated by Django 5.2.8 on 2025-11-22 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0007_bache_comentario_municipio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, max_length=15)),
                ('comentario_anterior', models.TextField(blank=True)),
                ('comentario_nuevo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='baches.bache')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de estado'), ('comentario', 'Comentario del municipio'), ('mixto', 'Estado y comentario')], default='estado', max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='baches.bache')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
