# Generated by Django 5.2.8 on 2025-11-25 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0008_historialbache_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bache',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='baches_votados', to=settings.AUTH_USER_MODEL),
        ),
    ]
