# Generated by Django 5.2.8 on 2025-11-28 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0009_bache_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('verify', 'Verificación'), ('reset', 'Recuperación')], max_length=10)),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vence', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
