# Generated by Django 5.2.8 on 2025-11-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0010_codigoemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigoemail',
            old_name='creado',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='codigoemail',
            old_name='vence',
            new_name='expira_en',
        ),
    ]
