# Generated by Django 5.2.8 on 2025-12-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baches', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenBache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='baches/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='baches.bache')),
            ],
        ),
    ]
